/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihan5;

/**
 *
 * @author Ridha Nadhira F
 */
public class lat5frame extends javax.swing.JFrame {

    /**
     * Creates new form lat5frame
     */
    public lat5frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        hb3 = new javax.swing.JTextField();
        hb2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        hb1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dskn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnProses = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Harga barang 3");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 130, 110, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Pembayaran");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 0, 130, 40);

        hb3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(hb3);
        hb3.setBounds(190, 140, 120, 30);

        hb2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(hb2);
        hb2.setBounds(190, 100, 120, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Harga barang 2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 90, 110, 40);

        hb1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(hb1);
        hb1.setBounds(190, 60, 120, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Harga barang 1 ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 50, 110, 40);

        dskn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(dskn);
        dskn.setBounds(190, 180, 120, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Diskon");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 170, 110, 40);

        btnProses.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });
        getContentPane().add(btnProses);
        btnProses.setBounds(120, 230, 140, 30);

        TA.setColumns(20);
        TA.setRows(5);
        jScrollPane1.setViewportView(TA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 280, 280, 120);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 380, 430);

        setBounds(0, 0, 393, 473);
    }// </editor-fold>//GEN-END:initComponents

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        // TODO add your handling code here:
        int barang1 = Integer.parseInt(hb1.getText());
        int barang2 = Integer.parseInt(hb2.getText());
        int barang3 = Integer.parseInt(hb3.getText());
        int diskon = Integer.parseInt(dskn.getText());
        double total = (barang1+barang2+barang3);
        double totalbayar = (barang1+barang2+barang3)-(barang1+barang2+barang3)*diskon/100;
        
        TA.setText("Harga Barang 1 : "+barang1+"\nHarga Barang 2 : "+barang2
                +"\nHarga Barang 3 : "+barang3+"\n Total Harga : "+total+"\n Diskon : "+diskon
        +"\n Total Bayar : "+totalbayar);
    }//GEN-LAST:event_btnProsesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lat5frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lat5frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lat5frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lat5frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lat5frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TA;
    private javax.swing.JButton btnProses;
    private javax.swing.JTextField dskn;
    private javax.swing.JTextField hb1;
    private javax.swing.JTextField hb2;
    private javax.swing.JTextField hb3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
